name: CI

on:
  push:
    branches:
      - master
  pull_request:

jobs:
  test:
    runs-on: macOS-latest
    env:
      WORKSPACE: HLSCachingReverseProxyServer.xcworkspace
      SCHEME: HLSCachingReverseProxyServer-Package
      SDK: iphonesimulator
      DESTINATION: platform=iOS Simulator,name=iPhone 11 Pro,OS=latest

    steps:
    - uses: actions/checkout@v1

    - name: Generate Xcode Project
      run: make project

    - name: Build and Test
      run: |
        set -o pipefail && xcodebuild clean build test \
          -workspace "$WORKSPACE" \
          -scheme "$SCHEME" \
          -sdk "$SDK" \
          -destination "$DESTINATION" \
          -configuration Debug \
          -enableCodeCoverage YES \
          CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO | xcpretty -c

    - name: Upload Code Coverage
      run: |
        bash <(curl -s https://codecov.io/bash) \
          -X xcodeplist \
          -J HLSCachingReverseProxyServer \
          -t "$CODECOV_TOKEN"
      env:
        CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
